name: python-public-policy
channels:
  - default
  - conda-forge
dependencies:
  # local development
  - RISE
  - ipykernel
  - jupyter_contrib_nbextensions
  - notebook
  - nb_conda
  # packages used in notebooks
  - pandas=1.*.*
  - plotly=5.*.*
  - statsmodels=0.*.*
  # https://plotly.com/python/static-image-export/
  - python-kaleido
  # CI
  - nbconvert
  - nbdime
  - pytest
  # other
  - requests
