name: python-public-policy-jupyter-book
channels:
  # in opposite order from ../environment.yml due to some resolver issue
  - conda-forge
  - defaults
dependencies:
  # this needs to stay in sync with ../environment.yml
  - jupyter-book=1.0.3
  # https://github.com/sphinx-doc/sphinx/issues/10440#issuecomment-1556180835
  - sphinx>=6.2.0
